## base yml file for all services in the config service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}


spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:29092
      default:
        contentType: application/json
        group: ${spring.application.name}-group

management:
  endpoints:
    web:
      exposure:
        include: busrefresh, health, info, refresh
  info:
    env:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    description: Vet-Connect ${spring.application.name} Management Service updated again

    version: 1.0.0











