## local auth microservice yml file
spring:
  cloud:
    stream:
      bindings:
        deleteUser-out-0:
          destination: delete-user-request

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/auth_db
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format-sql: true

jwt:
  secret: ${JWT_SECRET}
