## notification yml file
spring:
  cloud:
    function:
      definition: >
        userRegistrationComplete;
        deleteUserComplete;
    stream:
      bindings:
        userRegistrationComplete-in-0:
          destination: create-user-complete
        deleteUserComplete-in-0:
          destination: delete-user-complete

  mail:
    host: smtp.gmail.com
    port: 587
    username: petuniversal8@gmail.com
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


